"""
IEEE Robotics & Automation Society - Vercel Python Entrypoint
Handles routing, static file delivery, and serverless Cloud PostgreSQL REST API.
"""
import os
import json
import mimetypes
from http.server import BaseHTTPRequestHandler
import db

# Auto-generate scripts/config.js from environment variables if not present
def init_environment_config():
    try:
        scripts_dir = os.path.join(os.path.dirname(__file__), "scripts")
        config_path = os.path.join(scripts_dir, "config.js")
        
        if not os.path.exists(config_path):
            os.makedirs(scripts_dir, exist_ok=True)
            env_vars = {
                "DEFAULT_LEAD_PASSWORD": os.environ.get("DEFAULT_LEAD_PASSWORD", "lead123"),
                "DEFAULT_MEMBER_PASSWORD": os.environ.get("DEFAULT_MEMBER_PASSWORD", "member123"),
                "DEFAULT_PARTICIPANT_PASSWORD": os.environ.get("DEFAULT_PARTICIPANT_PASSWORD", "participant123"),
                "LEAD_NAME": os.environ.get("LEAD_NAME", "XYZ"),
                "LEAD_EMAIL": os.environ.get("LEAD_EMAIL", "xyz@vitstudent.ac.in"),
                "LEAD_GITHUB_USER": os.environ.get("LEAD_GITHUB_USER", "xyz"),
                "LEAD_GITHUB_URL": os.environ.get("LEAD_GITHUB_URL", "https://github.com/xyz"),
                "LEAD_LINKEDIN_URL": os.environ.get("LEAD_LINKEDIN_URL", "https://linkedin.com/in/xyz"),
                "GITHUB_REPO_URL": os.environ.get("GITHUB_REPO_URL", "https://github.com/xyz/ieee-ras-website"),
                "GEMINI_API_KEY": os.environ.get("GEMINI_API_KEY", ""),
                "WEBRTC_SIGNALING_URL": os.environ.get("WEBRTC_SIGNALING_URL", "https://meet.ieee-ras.org")
            }
            with open(config_path, "w", encoding="utf-8") as f:
                f.write("/**\n * Auto-generated by Python entrypoint from environment variables\n */\n")
                f.write("window.__ENV__ = " + json.dumps(env_vars, indent=2) + ";\n")
            print("Successfully initialized scripts/config.js from environment variables.")
    except Exception as e:
        print(f"Notice: Config initialization handled gracefully: {e}")

init_environment_config()

# Auto-initialize database schema and seed defaults if DATABASE_URL is present
try:
    if db.get_db_url():
        success, msg = db.init_db()
        print(f"Database bootstrap: {msg}")
except Exception as e:
    print(f"Database bootstrap note: {e}")

class handler(BaseHTTPRequestHandler):
    def _send_json(self, status_code, data):
        """Helper to send JSON response with CORS headers."""
        payload = json.dumps(data).encode("utf-8")
        self.send_response(status_code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(payload)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization")
        self.send_header("Cache-Control", "no-cache, no-store, must-revalidate")
        self.end_headers()
        self.wfile.write(payload)

    def do_OPTIONS(self):
        """Handle CORS pre-flight requests."""
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization")
        self.end_headers()

    def do_GET(self):
        clean_path = self.path.split("?")[0].lstrip("/")
        
        # --- API Routes ---
        if clean_path.startswith("api/"):
            endpoint = clean_path[4:]
            if endpoint == "health":
                return self._send_json(200, db.check_db_status())
            elif endpoint == "members":
                return self._send_json(200, db.get_members())
            elif endpoint == "participants":
                return self._send_json(200, db.get_participants())
            elif endpoint == "commits":
                return self._send_json(200, db.get_commits())
            elif endpoint == "init-db":
                ok, msg = db.init_db()
                return self._send_json(200 if ok else 500, {"success": ok, "message": msg})
            else:
                return self._send_json(404, {"error": f"Unknown API endpoint: /{clean_path}"})

        # --- Static File Serving ---
        if not clean_path:
            clean_path = "index.html"

        base_dir = os.path.dirname(__file__)
        file_path = os.path.join(base_dir, clean_path)

        # Fallback to index.html for root or SPA paths
        if not os.path.exists(file_path) or os.path.isdir(file_path):
            file_path = os.path.join(base_dir, "index.html")

        # Determine MIME type
        mime_type, _ = mimetypes.guess_type(file_path)
        if not mime_type:
            if file_path.endswith(".js"):
                mime_type = "application/javascript"
            elif file_path.endswith(".css"):
                mime_type = "text/css"
            elif file_path.endswith(".html"):
                mime_type = "text/html"
            else:
                mime_type = "application/octet-stream"

        try:
            with open(file_path, "rb") as f:
                content = f.read()

            self.send_response(200)
            self.send_header("Content-Type", f"{mime_type}; charset=utf-8" if "text" in mime_type or "javascript" in mime_type else mime_type)
            self.send_header("Content-Length", str(len(content)))
            self.send_header("Cache-Control", "public, max-age=3600")
            self.end_headers()
            self.wfile.write(content)
        except Exception as err:
            self.send_response(500)
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            self.wfile.write(f"Server Error: {err}".encode("utf-8"))

    def do_POST(self):
        clean_path = self.path.split("?")[0].lstrip("/")
        
        # Read request body
        try:
            content_length = int(self.headers.get("Content-Length", 0))
            raw_data = self.rfile.read(content_length) if content_length > 0 else b"{}"
            data = json.loads(raw_data.decode("utf-8")) if raw_data else {}
        except Exception as e:
            return self._send_json(400, {"error": f"Invalid JSON payload: {e}"})

        # --- API Routes ---
        if clean_path.startswith("api/"):
            endpoint = clean_path[4:]
            if endpoint == "members":
                if isinstance(data, list):
                    saved_list = [db.save_member(m) for m in data]
                    return self._send_json(200, {"success": True, "members": saved_list})
                else:
                    saved = db.save_member(data)
                    return self._send_json(200, {"success": True, "member": saved})

            elif endpoint == "participants":
                if isinstance(data, list):
                    saved_list = [db.save_participant(p) for p in data]
                    return self._send_json(200, {"success": True, "participants": saved_list})
                else:
                    saved = db.save_participant(data)
                    return self._send_json(200, {"success": True, "participant": saved})

            elif endpoint == "commits":
                saved = db.save_commit(data)
                return self._send_json(200, {"success": True, "commit": saved})

            elif endpoint == "init-db":
                ok, msg = db.init_db()
                return self._send_json(200 if ok else 500, {"success": ok, "message": msg})

            else:
                return self._send_json(404, {"error": f"Unknown API endpoint: /{clean_path}"})

        return self._send_json(404, {"error": "Endpoint not found"})

# WSGI compatibility alias for WSGI servers
app = handler
